### ISSUE TITLE
Not sure if RETAIN_N_DAYS is working

### ISSUE THREAD

**Issue by stayupthetree** [mbround18/backup-docker#3]
I've been running with the setup for palworld backups, I noticed this in the logs 

> Namespace(source='/home/steam/palworld/Pal/Saved/', destination='/home/steam/backups', user='99', group='100', keep_n_days=0, keep_n_files=0)

I had it set to 14 days. I changed it to 1 to see if maybe it just didn't show the right number in the logs but pruned appropriately. It did not

**Comment by mbround18** [comment]
Can yoh share your docker Compose?

**Comment by stayupthetree** [comment]
backups:
    container_name: palworld-backups
    image: mbround18/backup-cron:latest
    environment:
      - SCHEDULE=*/5 * * * *
      - INPUT_FOLDER=/home/steam/palworld/Pal/Saved/
      - OUTPUT_FOLDER=/home/steam/backups
      - OUTPUT_USER=99
      - OUTPUT_GROUP=100
      - RETAIN_N_DAYS=1
    volumes:
      - /mnt/user/appdata/Palworld:/home/steam/palworld
      - /mnt/user/data/backups/Palworld:/home/steam/backups
    restart: unless-stopped

**Comment by mbround18** [comment]
@stayupthetree this logic has been fixed, would you mine pulling latest and retrying? if youd like add a `DRY_RUN=true` to just see it execute and what i would have deleted.

**Comment by stayupthetree** [comment]
Looks like it will make a save and then instantly delete it now. I set the days to 2. Log still showing 0.

------------------------------------------------------------------
Starting backup cron job - Mon Jan 29 12:52:09 UTC 2024
Schedule: */5 * * * *
Input folder: /home/steam/palworld/Pal/Saved/
Output folder: /home/steam/backups
User: 99
Group: 100
Installing Cron:
*/5 * * * * DRY_RUN=true INPUT_FOLDER=/home/steam/palworld/Pal/Saved/ OUTPUT_FOLDER=/home/steam/backups OUTPUT_USER=99 OUTPUT_GROUP=100 KEEP_N_DAYS=0 KEEP_N_FILES=0 /usr/local/bin/python /app/main.py>> /var/log/cron.log 2>&1
------------------------------------------------------------------
Running Initial Backup...
Namespace(source='/home/steam/palworld/Pal/Saved/', destination='/home/steam/backups', user='99', group='100', keep_n_days=0, keep_n_files=0)
Zipping folder /home/steam/palworld/Pal/Saved/ to /home/steam/backups...
Folder /home/steam/palworld/Pal/Saved/ zipped successfully to /home/steam/backups/Saved_20240129_125209.zip (3.11 MB)
Adjusting file retention for /home/steam/backups...
keep_n_files: 0
keep_n_days: 0
Would delete Saved_20240129_125028.zip
Would delete Saved_20240129_125209.zip

**Comment by stayupthetree** [comment]
ooo I changed the variable from RETAIN_N_DAYS to KEEP_N_DAYS and its working. 

Installing Cron:
*/5 * * * * DRY_RUN=true INPUT_FOLDER=/home/steam/palworld/Pal/Saved/ OUTPUT_FOLDER=/home/steam/backups OUTPUT_USER=99 OUTPUT_GROUP=100 KEEP_N_DAYS=2 KEEP_N_FILES=0 /usr/local/bin/python /app/main.py>> /var/log/cron.log 2>&1
------------------------------------------------------------------
Running Initial Backup...
Namespace(source='/home/steam/palworld/Pal/Saved/', destination='/home/steam/backups', user='99', group='100', keep_n_days=2, keep_n_files=0)
Zipping folder /home/steam/palworld/Pal/Saved/ to /home/steam/backups...
Folder /home/steam/palworld/Pal/Saved/ zipped successfully to /home/steam/backups/Saved_20240129_125742.zip (3.12 MB)
Adjusting file retention for /home/steam/backups...
keep_n_files: 0
keep_n_days: 2

**Comment by mbround18** [comment]
Found that issue as well, keep_n_files and keep n days was sorting incorrectly

**Comment by mbround18** [comment]
refactored and functioned the logic, works very well with both flags and the day can be decimal now. allowing you to do something like a half day or even get as tricky as 5m `0.003472`

**Comment by stayupthetree** [comment]
Everything is working great! Thank you for looking into this
